# Generated by Django 5.0.4 on 2024-05-21 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("tester", "Tester"),
                    ("viewer", "Viewer"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
