# Generated by Django 5.0.4 on 2024-05-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_appuser_date_joined_appuser_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="date_joined",
        ),
        migrations.AlterField(
            model_name="appuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("tester", "Tester"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=10,
            ),
        ),
    ]
